# Затемнение экрана через гамму
# listener {
#   timeout = 120
#   on-timeout = ddcutil setvcp 10 20
#   on-resume = ddcutil setvcp 10 65
# }


# DPMS - выключение/включение монитора
listener {
  timeout = 400
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}


# Блокировка экрана
listener {
  timeout = 1200
  on-timeout = hyprlock -c ~/.config/hypr/$theme/hyprlock.conf 
}
